version: "3.8"

services:
  papoca-scan:
    build: .
    container_name: papoca-scan
    restart: always
    ports:
      - "3000:3000"
    networks:
      - rede-proxy
    environment:
      - UPSTASH_REDIS_REST_URL=${UPSTASH_REDIS_REST_URL}
      - UPSTASH_REDIS_REST_TOKEN=${UPSTASH_REDIS_REST_TOKEN}

networks:
  rede-proxy:
    external: true
